// <auto-generated />
using BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObjects.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241002115502_SeedProductData")]
    partial class SeedProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Beverages"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Condiments"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Confections"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dairy Products"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Grains/Cereals"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Meat/Poultry"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Produce"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Seafood"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 3,
                            ProductName = "Apple iPhone 14",
                            UnitPrice = 999.99m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3,
                            ProductName = "Samsung Galaxy S22",
                            UnitPrice = 799.99m,
                            UnitsInStock = 150
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 5,
                            ProductName = "Sony WH-1000XM5 Headphones",
                            UnitPrice = 299.99m,
                            UnitsInStock = 200
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            ProductName = "Dell XPS 13 Laptop",
                            UnitPrice = 1500.00m,
                            UnitsInStock = 80
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            ProductName = "Apple MacBook Pro",
                            UnitPrice = 2300.00m,
                            UnitsInStock = 50
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 7,
                            ProductName = "Amazon Echo Dot",
                            UnitPrice = 49.99m,
                            UnitsInStock = 300
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 6,
                            ProductName = "Bose SoundLink Speaker",
                            UnitPrice = 199.99m,
                            UnitsInStock = 120
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            ProductName = "Google Pixel 7",
                            UnitPrice = 899.99m,
                            UnitsInStock = 90
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            ProductName = "HP Envy 15 Laptop",
                            UnitPrice = 1399.99m,
                            UnitsInStock = 60
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            ProductName = "Lenovo ThinkPad X1 Carbon",
                            UnitPrice = 1799.99m,
                            UnitsInStock = 70
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            ProductName = "Apple iPad Pro",
                            UnitPrice = 1099.99m,
                            UnitsInStock = 130
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            ProductName = "Microsoft Surface Laptop 4",
                            UnitPrice = 1199.99m,
                            UnitsInStock = 110
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 6,
                            ProductName = "JBL Charge 5 Speaker",
                            UnitPrice = 149.99m,
                            UnitsInStock = 240
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5,
                            ProductName = "OnePlus 9 Pro",
                            UnitPrice = 799.99m,
                            UnitsInStock = 90
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 7,
                            ProductName = "Asus ROG Zephyrus Gaming Laptop",
                            UnitPrice = 2199.99m,
                            UnitsInStock = 30
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 1,
                            ProductName = "Fitbit Versa 3",
                            UnitPrice = 229.99m,
                            UnitsInStock = 400
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 8,
                            ProductName = "Sony PlayStation 5",
                            UnitPrice = 499.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 7,
                            ProductName = "Apple AirPods Pro",
                            UnitPrice = 249.99m,
                            UnitsInStock = 350
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 6,
                            ProductName = "GoPro HERO10",
                            UnitPrice = 399.99m,
                            UnitsInStock = 90
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 8,
                            ProductName = "Nikon D7500 Camera",
                            UnitPrice = 1199.99m,
                            UnitsInStock = 40
                        });
                });

            modelBuilder.Entity("BusinessObjects.Product", b =>
                {
                    b.HasOne("BusinessObjects.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjects.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
